from __future__ import annotations

from collections.abc import Iterable


YOGA_TOPICS: dict[str, str] = {
    "asana": "Asana means a yoga posture. In modern practice it usually refers to physical poses used to train mobility, strength, balance, and body awareness.",
    "pranayama": "Pranayama is breath regulation in yoga. It is used to steady attention, calm the nervous system, and build better breathing control.",
    "meditation": "Meditation in yoga trains attention and awareness. A simple start is sitting comfortably and returning attention to the breath when the mind wanders.",
    "mindfulness": "Mindfulness means paying attention to the present moment without rushing to judge it. Yoga uses it to connect breath, movement, and awareness.",
    "sun salutation": "Sun salutation is a flowing sequence of poses often used as a warm-up. It links breath with movement and gently builds heat.",
    "mountain pose": "Mountain pose is a standing posture for alignment. Stand tall, ground the feet, relax the shoulders, and lengthen through the crown of the head.",
    "downward dog": "Downward dog stretches the back body and strengthens the shoulders. Keep the spine long, bend the knees if needed, and press the floor away.",
    "child pose": "Child pose is a resting posture. It gently relaxes the back, hips, and shoulders and is useful whenever practice feels too intense.",
    "cat cow": "Cat-cow moves the spine between rounding and arching. It is a gentle way to warm up the back and coordinate breath with movement.",
    "cobra pose": "Cobra pose is a mild backbend. Press the tops of the feet down, lift the chest gently, and avoid forcing the lower back.",
    "plank pose": "Plank builds core, shoulder, and leg strength. Keep the body long and steady rather than letting the hips sag.",
    "warrior one": "Warrior one builds leg strength and hip mobility. Square the torso forward as much as comfortable and keep the front knee tracking safely.",
    "warrior two": "Warrior two develops stamina, balance, and grounded focus. Open the hips, reach through both arms, and soften the shoulders.",
    "triangle pose": "Triangle pose stretches the side body and hamstrings. Hinge from the hip and keep the chest open rather than collapsing downward.",
    "tree pose": "Tree pose trains balance and concentration. Place the foot above or below the knee, never pressing directly into the knee joint.",
    "chair pose": "Chair pose strengthens the legs and core. Sit the hips back, keep the chest lifted, and breathe steadily.",
    "bridge pose": "Bridge pose strengthens the back body and opens the front of the hips. Lift through the hips without squeezing the neck.",
    "corpse pose": "Corpse pose is final relaxation. It lets the body settle and helps the nervous system absorb the practice.",
    "savasana": "Savasana is final relaxation. Lie comfortably, release effort, and let the breath return to a natural rhythm.",
    "vinyasa": "Vinyasa is a flowing style of yoga where movements are linked with breath. It can feel dynamic, so beginners should move slowly and modify.",
    "hatha": "Hatha yoga usually means a slower practice focused on poses, breath, and alignment. It is often a good starting point for beginners.",
    "yin yoga": "Yin yoga uses long-held, mostly floor-based poses. It targets connective tissue and encourages stillness, patience, and gentle release.",
    "restorative yoga": "Restorative yoga uses props and comfortable holds to support deep rest. It is useful for relaxation and recovery.",
    "power yoga": "Power yoga is a stronger, fitness-oriented style. It can build stamina, but beginners should protect joints and avoid rushing.",
    "hot yoga": "Hot yoga is practiced in a heated room. Hydration, pacing, and stopping if dizzy are important.",
    "kundalini yoga": "Kundalini yoga combines movement, breath, chanting, and meditation. It emphasizes energy and awareness practices.",
    "iyengar yoga": "Iyengar yoga emphasizes precise alignment and often uses props. It can be helpful for learning safe pose mechanics.",
    "ashtanga yoga": "Ashtanga yoga follows set sequences and is physically demanding. Beginners should learn gradually with careful pacing.",
    "beginner yoga": "Beginner yoga should focus on simple poses, easy breathing, and consistency. Comfort and safe alignment matter more than depth.",
    "yoga benefits": "Yoga may support flexibility, strength, balance, stress reduction, and body awareness. Benefits come best from steady, comfortable practice.",
    "flexibility": "Yoga can improve flexibility by gently loading tissues over time. Progress is usually gradual, so forcing stretches is not useful.",
    "mobility": "Mobility is controlled range of motion. Yoga can help by combining stretching, strength, balance, and breath awareness.",
    "balance": "Yoga improves balance by training foot stability, core control, and attention. Tree pose and warrior poses are common starting points.",
    "strength": "Yoga builds strength through bodyweight positions such as plank, chair, bridge, and warrior poses.",
    "stress": "Yoga can reduce stress by slowing breathing, relaxing muscle tension, and giving the mind a clear focus.",
    "anxiety": "Yoga may help manage mild anxiety through breath, movement, and grounding. It is not a replacement for professional care when symptoms are severe.",
    "sleep": "Gentle yoga before bed can help some people relax. Choose slow stretches, easy breathing, and avoid intense flows late at night.",
    "breathing": "Yoga breathing should feel steady and comfortable. If breath control causes dizziness or strain, return to normal breathing.",
    "diaphragmatic breathing": "Diaphragmatic breathing encourages the belly and ribs to expand on inhale. It can support relaxation and efficient breathing.",
    "box breathing": "Box breathing uses equal counts for inhale, hold, exhale, and hold. Keep the count easy and stop if it feels uncomfortable.",
    "alternate nostril breathing": "Alternate nostril breathing is a pranayama practice that alternates airflow through each nostril. It is often used for calm focus.",
    "ujjayi breath": "Ujjayi breath uses a soft throat tone during breathing. It can help pace movement in flowing yoga.",
    "alignment": "Yoga alignment means arranging the body so a pose is stable and comfortable. Good alignment reduces strain and improves awareness.",
    "props": "Yoga props such as blocks, straps, bolsters, and blankets make poses more accessible and safer.",
    "yoga block": "A yoga block brings the floor closer and supports alignment. It is useful in standing folds, triangle pose, and seated stretches.",
    "yoga strap": "A yoga strap extends reach without forcing joints. It helps with hamstring stretches, shoulder mobility, and gentle binds.",
    "warm up": "A yoga warm-up prepares joints and muscles with easy movements such as cat-cow, shoulder rolls, and gentle lunges.",
    "cool down": "A yoga cool-down uses slower stretches and relaxation to lower intensity and settle the breath.",
    "back pain": "Gentle yoga may help some back discomfort, but sharp pain, numbness, or injury needs professional medical guidance.",
    "neck pain": "For neck discomfort, use gentle range of motion and avoid forcing stretches. Persistent or severe pain should be checked by a professional.",
    "knee safety": "Knee safety in yoga means keeping knees tracking comfortably and using props or modifications when kneeling or lunging hurts.",
    "wrist safety": "Wrist safety means spreading the hands, pressing through the fingers, and modifying weight-bearing poses if wrists hurt.",
    "hip opening": "Hip-opening poses work mobility around the pelvis. They should feel spacious, not sharp or pinching.",
    "hamstrings": "Hamstring stretches work best with a long spine and slightly bent knees. Forcing straight legs can strain the back or tendons.",
    "shoulders": "Yoga shoulder work can improve mobility and stability. Keep the neck relaxed and avoid pushing into painful ranges.",
    "core": "Yoga core work supports posture and spinal stability. Plank, boat, and dead-bug style movements are common options.",
    "pelvic floor": "Yoga can include awareness of the pelvic floor, but symptoms like pain or leakage deserve guidance from a qualified clinician.",
    "prenatal yoga": "Prenatal yoga should be adapted for pregnancy and guided by medical advice. Comfort, breathing, and safety are the priorities.",
    "chair yoga": "Chair yoga adapts poses for seated or supported practice. It is useful for limited mobility, office breaks, or gentle recovery.",
    "office yoga": "Office yoga uses small movements such as neck rolls, seated twists, wrist stretches, and breathing breaks.",
    "morning yoga": "Morning yoga can be simple: gentle spinal movement, standing stretches, and a few steady breaths to start the day.",
    "evening yoga": "Evening yoga should be calming. Slow folds, supported poses, and relaxed breathing work better than intense sequences.",
    "yoga routine": "A balanced yoga routine includes warm-up, standing or strength work, mobility, breathing, and relaxation.",
    "yoga frequency": "For many people, ten to twenty minutes several times per week is better than one hard session done rarely.",
    "yoga and fitness": "Yoga can complement fitness by improving mobility, balance, recovery, breathing, and body control.",
    "yoga for athletes": "Yoga for athletes often focuses on mobility, recovery, breath control, and joint stability rather than extreme flexibility.",
    "yoga for seniors": "Yoga for seniors should emphasize balance, joint-friendly movement, breathing, and support from props or chairs when needed.",
    "yoga for kids": "Yoga for kids works best when it is playful, short, and focused on movement, breath, and body awareness.",
    "yoga history": "Yoga has roots in ancient India and includes philosophy, meditation, breath, ethics, and physical practices.",
    "eight limbs": "The eight limbs of yoga describe a path including ethics, posture, breath, sense withdrawal, concentration, meditation, and absorption.",
    "yamas": "Yamas are ethical guidelines in yoga, often described as non-harming, truthfulness, non-stealing, moderation, and non-greed.",
    "niyamas": "Niyamas are personal observances such as cleanliness, contentment, discipline, self-study, and dedication.",
    "ahimsa": "Ahimsa means non-harming. In practice, it includes moving without forcing and treating yourself and others with care.",
    "santosha": "Santosha means contentment. In yoga it encourages practicing with acceptance instead of constant comparison.",
    "drishti": "Drishti is a steady gaze point. It helps balance, attention, and mental focus during poses.",
    "bandha": "Bandhas are energetic or muscular locks used in some yoga traditions. They should be learned carefully and gently.",
    "mantra": "A mantra is a repeated sound, word, or phrase used to focus the mind during meditation or practice.",
    "om": "Om is a traditional sacred sound used in some yoga practices. It can mark the beginning or end of meditation.",
    "chakra": "Chakras are energy centers in yogic tradition. Some people use them as symbolic tools for reflection and meditation.",
    "mudra": "Mudras are hand gestures or energetic seals used in meditation and breath practices.",
    "yoga mat": "A yoga mat gives traction and cushioning. Choose one that prevents slipping and supports your joints comfortably.",
    "hydration": "Hydration matters, especially in warm or vigorous practice. Drink normally and pay attention to thirst and dizziness.",
    "overstretching": "Overstretching can irritate joints or connective tissue. A useful stretch feels manageable and steady, not sharp.",
    "modifications": "Yoga modifications make poses fit the body. Using props, bending knees, or reducing range is skilled practice, not failure.",
    "breath with movement": "Linking breath with movement helps regulate pace and focus. A common pattern is inhale to lengthen, exhale to fold or twist.",
    "seated forward fold": "Seated forward fold stretches the back body. Bend the knees and hinge from the hips to avoid rounding aggressively.",
    "pigeon pose": "Pigeon pose targets hip rotation. If the knee feels strained, use a figure-four stretch or props instead.",
    "lizard pose": "Lizard pose opens the hips and hip flexors. Use blocks under the hands and keep the front knee comfortable.",
    "low lunge": "Low lunge stretches the hip flexors and builds balance. Pad the back knee if needed and keep the front knee steady.",
    "high lunge": "High lunge strengthens legs and improves balance. Keep the back leg active and the breath steady.",
    "half moon": "Half moon is a balancing pose that opens the hips and chest. A block under the lower hand makes it more accessible.",
    "boat pose": "Boat pose strengthens the core and hip flexors. Keep the spine long and bend the knees if the back rounds.",
    "eagle pose": "Eagle pose challenges balance and stretches the upper back. The full wrap is optional; stability matters more.",
    "crow pose": "Crow pose is an arm balance requiring wrist, core, and shoulder control. Learn it gradually with padding and supervision if needed.",
    "headstand": "Headstand is an advanced inversion with neck risk. It should be learned carefully from a qualified teacher, and many people should skip it.",
    "shoulderstand": "Shoulderstand is an advanced inversion that can stress the neck. Use expert guidance and avoid it if it feels unsafe.",
    "twists": "Yoga twists can improve spinal awareness and gentle mobility. Lengthen first, twist gently, and avoid forcing range.",
    "inversions": "Inversions put the head below the heart. They can be intense, so beginners should start with mild options like legs up the wall.",
    "legs up the wall": "Legs up the wall is a gentle restorative pose. It can help relaxation and reduce leg fatigue for some people.",
    "body scan": "A body scan brings attention through different body areas. It is a simple meditation tool for relaxation and awareness.",
    "yoga safety": "Yoga safety means moving gradually, breathing comfortably, modifying poses, and stopping if there is sharp pain, dizziness, or numbness.",
}


CYBERSECURITY_TOPICS: dict[str, str] = {
    "cybersecurity": "Cybersecurity protects systems, networks, accounts, and data from unauthorized access, damage, or misuse.",
    "phishing": "Phishing is a trick that tries to steal information through fake messages or websites. Verify senders, avoid suspicious links, and use MFA.",
    "spear phishing": "Spear phishing targets a specific person or organization. Defend with verification habits, security awareness, and strong email controls.",
    "smishing": "Smishing is phishing through text messages. Treat urgent links and account warnings with suspicion and verify through official channels.",
    "vishing": "Vishing is voice-based phishing. Do not share codes or passwords on calls, and call organizations back using trusted numbers.",
    "malware": "Malware is software designed to harm, spy, steal, or disrupt. Reduce risk with patching, backups, least privilege, and reputable protection.",
    "ransomware": "Ransomware encrypts or steals data to demand payment. Backups, patching, segmentation, MFA, and tested recovery plans are key defenses.",
    "spyware": "Spyware secretly monitors activity or steals data. Keep devices updated, avoid untrusted downloads, and review permissions.",
    "hacking": "Hacking means finding ways to make systems do things they were not intended to do. Keep it ethical and authorized: learn in labs, document findings, and focus on defense.",
    "trojan": "A trojan pretends to be legitimate software while hiding malicious behavior. Install software only from trusted sources.",
    "worm": "A worm spreads across systems without much user interaction. Patching, segmentation, and network monitoring reduce worm risk.",
    "botnet": "A botnet is a group of compromised devices controlled remotely. Strong passwords, updates, and network monitoring help prevent enrollment.",
    "password": "A strong password is long, unique, and hard to guess. A password manager makes unique passwords practical.",
    "password manager": "A password manager stores unique passwords securely and reduces reuse. Protect it with a strong master password and MFA.",
    "passkey": "A passkey is a phishing-resistant sign-in method based on public-key cryptography. It is safer and easier than many passwords.",
    "mfa": "Multi-factor authentication adds another proof beyond a password. App-based codes, hardware keys, or passkeys are stronger than SMS.",
    "2fa": "Two-factor authentication is a form of MFA using two proofs. It greatly reduces account takeover risk.",
    "hardware security key": "A hardware security key is a physical MFA device. It is one of the strongest defenses against phishing.",
    "encryption": "Encryption protects data by making it unreadable without the right key. It helps secure files, disks, messages, and network traffic.",
    "hashing": "Hashing turns data into a fixed fingerprint. It is useful for integrity checks and password storage when combined with salts.",
    "salting": "A salt is random data added before hashing a password. It makes precomputed password attacks much harder.",
    "vpn": "A VPN encrypts traffic between your device and the VPN provider. It helps on untrusted networks but does not make all activity anonymous.",
    "firewall": "A firewall controls network traffic by rules. It can reduce exposure by allowing only needed connections.",
    "network segmentation": "Network segmentation separates systems into zones. It limits how far an incident can spread.",
    "zero trust": "Zero trust means verify explicitly, use least privilege, and assume networks are not automatically trusted.",
    "least privilege": "Least privilege gives users and services only the access they need. It limits damage from mistakes or compromise.",
    "patching": "Patching updates software to fix vulnerabilities. Timely patching is one of the most effective defenses.",
    "vulnerability": "A vulnerability is a weakness that could be exploited. Managing vulnerabilities means finding, prioritizing, and fixing them.",
    "cve": "A CVE is a public identifier for a known vulnerability. It helps teams track and discuss specific security issues.",
    "cvss": "CVSS is a scoring system for vulnerability severity. It helps prioritize, but real business context still matters.",
    "risk": "Cyber risk combines likelihood and impact. Good security focuses on reducing the most important risks first.",
    "threat": "A threat is a potential cause of harm, such as an attacker, insider, malware, or accident.",
    "asset": "An asset is something valuable to protect, such as data, accounts, devices, services, or reputation.",
    "attack surface": "Attack surface is the set of ways a system can be attacked. Reducing unused services and permissions lowers exposure.",
    "hardening": "Hardening means configuring systems securely by removing unnecessary features, closing exposures, and enforcing strong defaults.",
    "secure configuration": "Secure configuration means settings are chosen to reduce risk, such as disabling defaults, enforcing MFA, and limiting access.",
    "logging": "Security logging records important events. Useful logs help detect incidents, investigate activity, and prove what happened.",
    "monitoring": "Security monitoring watches systems and alerts on suspicious activity. It works best with clear baselines and tuned alerts.",
    "siem": "A SIEM collects and analyzes security logs. It helps teams detect, investigate, and respond to incidents.",
    "soc": "A security operations center monitors alerts, investigates threats, and coordinates response.",
    "edr": "Endpoint detection and response monitors computers for suspicious behavior and helps investigate or contain threats.",
    "antivirus": "Antivirus detects known malicious files and behavior. It is useful, but it should be part of layered defense.",
    "backup": "Backups protect against deletion, ransomware, and hardware failure. Keep offline or immutable copies and test restoration.",
    "incident response": "Incident response is the process for detecting, containing, eradicating, and recovering from a security event.",
    "containment": "Containment limits damage during an incident. Examples include isolating systems, disabling accounts, or blocking traffic.",
    "forensics": "Digital forensics preserves and analyzes evidence from systems. It focuses on facts, timelines, and root cause.",
    "chain of custody": "Chain of custody tracks who handled evidence and when. It supports trustworthy investigations.",
    "threat hunting": "Threat hunting is proactive searching for signs of compromise. It uses hypotheses, logs, and knowledge of attacker behavior.",
    "threat intelligence": "Threat intelligence is information about threats and attacker behavior. It is useful when it is relevant, timely, and actionable.",
    "ioc": "An indicator of compromise is evidence that suspicious activity may have occurred, such as a malicious hash, domain, or IP.",
    "ttp": "TTPs are tactics, techniques, and procedures. They describe how attackers operate at a behavior level.",
    "mitre attck": "MITRE ATT&CK is a knowledge base of attacker techniques. Defenders use it to map detections and improve coverage.",
    "security awareness": "Security awareness teaches people how to recognize and report risks like phishing, social engineering, and unsafe data handling.",
    "social engineering": "Social engineering manipulates people rather than technology. Verification habits and low-pressure processes reduce risk.",
    "privacy": "Privacy focuses on appropriate collection, use, sharing, and protection of personal information.",
    "data classification": "Data classification labels information by sensitivity. It helps apply the right controls to public, internal, confidential, or restricted data.",
    "data loss prevention": "Data loss prevention helps detect or block sensitive data leaving approved places. It works best with classification and clear policies.",
    "access control": "Access control decides who can use which resources. Strong identity, MFA, and least privilege are central.",
    "authentication": "Authentication proves identity. Passwords, passkeys, MFA, and certificates are common methods.",
    "authorization": "Authorization decides what an authenticated user is allowed to do. It should be specific and regularly reviewed.",
    "identity security": "Identity security protects accounts, roles, credentials, and authentication flows because identity is often the main attack path.",
    "privileged access": "Privileged access controls admin-level permissions. Use MFA, just-in-time access, logging, and separation of duties.",
    "session hijacking": "Session hijacking abuses a valid login session. Defenses include HTTPS, secure cookies, MFA, and session monitoring.",
    "cookie security": "Cookie security uses flags like HttpOnly, Secure, and SameSite to reduce theft and cross-site abuse.",
    "https": "HTTPS encrypts web traffic and authenticates websites. It protects against many network interception risks.",
    "ssh": "SSH, or Secure Shell, is a protocol for secure remote login and command-line access. Protect it with keys, strong access control, patching, and limited exposure.",
    "secure shell": "Secure Shell, or SSH, is a protocol for encrypted remote administration. Use keys, MFA where available, least privilege, and avoid exposing it broadly.",
    "tls": "TLS is the protocol behind HTTPS encryption. Good TLS configuration avoids weak versions and ciphers.",
    "certificate": "Digital certificates help prove a server or identity is legitimate. Expired or misissued certificates can break trust.",
    "dns security": "DNS security protects name resolution from abuse. Monitoring, filtering, and DNSSEC where appropriate can help.",
    "email security": "Email security combines filtering, authentication, user reporting, and safe handling of attachments and links.",
    "spf": "SPF is an email authentication control that lists which servers may send mail for a domain.",
    "dkim": "DKIM signs email so receivers can verify it was authorized and not altered in transit.",
    "dmarc": "DMARC tells receivers how to handle mail that fails SPF or DKIM checks and helps reduce spoofing.",
    "cloud security": "Cloud security protects cloud identities, data, networks, and configurations. Misconfiguration and excessive permissions are common risks.",
    "shared responsibility": "Shared responsibility means cloud providers secure some layers while customers secure their own data, identities, and configurations.",
    "container security": "Container security includes trusted images, scanning, least privilege, secrets protection, and runtime monitoring.",
    "kubernetes security": "Kubernetes security focuses on RBAC, network policies, secrets, image trust, patching, and workload isolation.",
    "api security": "API security protects interfaces with authentication, authorization, validation, rate limits, logging, and careful data exposure.",
    "web security": "Web security reduces risks in websites and apps through secure coding, validation, authentication, and monitoring.",
    "owasp": "OWASP provides widely used guidance for web application security risks and secure development practices.",
    "sql injection": "SQL injection happens when untrusted input changes database queries. Defenses include parameterized queries and input handling.",
    "xss": "Cross-site scripting injects script into web pages. Output encoding, content security policy, and safe frameworks reduce risk.",
    "csrf": "Cross-site request forgery tricks a browser into sending unwanted actions. SameSite cookies and CSRF tokens help defend.",
    "ssrf": "Server-side request forgery abuses a server into making unintended requests. Defenses include allowlists and metadata service protections.",
    "secure coding": "Secure coding means designing, writing, and reviewing software to reduce vulnerabilities before release.",
    "code review": "Security code review looks for risky patterns, missing checks, unsafe dependencies, and logic flaws.",
    "dependency security": "Dependency security tracks third-party packages, vulnerabilities, licenses, and supply-chain risk.",
    "supply chain security": "Supply-chain security protects build systems, dependencies, source control, artifacts, and release processes.",
    "secrets management": "Secrets management protects API keys, tokens, and passwords. Store secrets in approved vaults, not source code.",
    "api key": "API keys should be treated like credentials. Limit scope, rotate when exposed, and avoid hard-coding them.",
    "token": "Security tokens grant access and should be protected, scoped, monitored, and revoked when no longer needed.",
    "mobile security": "Mobile security includes device updates, app permissions, screen locks, encryption, and safe app installation.",
    "iot security": "IoT security focuses on changing default passwords, updating firmware, segmenting networks, and limiting exposed services.",
    "wifi security": "Wi-Fi security uses strong encryption, strong passwords, firmware updates, and guest networks for untrusted devices.",
    "router security": "Router security starts with firmware updates, strong admin passwords, disabled remote admin, and secure Wi-Fi settings.",
    "bluetooth security": "Bluetooth security means pairing only trusted devices, disabling discoverable mode when not needed, and keeping devices updated.",
    "physical security": "Physical security protects devices and facilities from theft, tampering, and unauthorized access.",
    "business continuity": "Business continuity plans keep critical services operating during disruption. They pair with disaster recovery plans.",
    "disaster recovery": "Disaster recovery restores systems after major failure. Recovery time and recovery point goals guide planning.",
    "compliance": "Compliance means meeting required laws, standards, or policies. It supports security but does not replace real risk management.",
    "policy": "A security policy sets expectations for behavior, controls, and responsibilities. Good policies are clear and enforceable.",
    "security training": "Security training builds habits for reporting, password safety, data handling, and recognizing social engineering.",
    "red team": "A red team emulates adversaries under authorization to test defenses and improve resilience.",
    "blue team": "A blue team defends systems through monitoring, hardening, detection, response, and recovery.",
    "purple team": "A purple team combines red and blue practices so offensive findings improve defensive controls.",
    "penetration test": "A penetration test is an authorized assessment of security weaknesses. It should have clear scope, rules, and reporting.",
    "vulnerability scan": "A vulnerability scan checks systems for known weaknesses. Results need validation and prioritization.",
    "security baseline": "A security baseline is a standard secure configuration. It helps keep systems consistent and auditable.",
    "asset inventory": "Asset inventory lists devices, software, services, and owners. You cannot protect what you do not know exists.",
}


def answer_domain_question(text: str) -> tuple[str, str] | None:
    normalized = _normalize(text)
    yoga = _find_topic(normalized, YOGA_TOPICS, required_terms=("yoga", "asana", "pose", "breath", "meditation"))
    if yoga is not None:
        return ("knowledge:yoga_catalog", yoga)
    cyber = _find_topic(
        normalized,
        CYBERSECURITY_TOPICS,
        required_terms=("cyber", "security", "phishing", "malware", "spyware", "hacking", "ssh", "password", "network", "privacy"),
    )
    if cyber is not None:
        return ("knowledge:cybersecurity_catalog", cyber)
    return None


def topic_counts() -> tuple[int, int]:
    return len(YOGA_TOPICS), len(CYBERSECURITY_TOPICS)


def _find_topic(
    text: str,
    topics: dict[str, str],
    required_terms: Iterable[str],
) -> str | None:
    ordered_topics = sorted(topics.items(), key=lambda item: len(item[0]), reverse=True)
    padded_text = f" {text} "
    for topic, answer in ordered_topics:
        if f" {topic} " in padded_text:
            return answer

    if not any(f" {term} " in padded_text for term in required_terms):
        return None

    for topic, answer in ordered_topics:
        words = topic.split()
        if any(f" {word} " in padded_text for word in words if len(word) >= 5):
            return answer
    return None


def _normalize(text: str) -> str:
    return " ".join(text.lower().replace("-", " ").split())
